sudo: required
services:
  - docker

before_install:
  - docker build -t malisahin/docker-react -f Dockerfile.dev .

script:
  #- docker run  malisahin/docker-react npm run test -- --coverage
  - docker run -e CI=true malisahin/docker-react npm run test -- --coverage

language: generic
