sudo: required
services:
  - docker

before_install:
  - docker build -t malisahin/docker-react -f Dockerfile.dev .

script:
  #- docker run  malisahin/docker-react npm run test -- --coverage
  - docker run -e CI=true malisahin/docker-react npm run test -- --coverage

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-055474306222"
  bucket_path: "docker"
